In [28]:
import numpy as np

x_data = [[[999,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]

In [29]:
x_data = np.asarray(x_data)

In [30]:
x_data.shape

(2, 3, 4)

In [31]:
x_data0 = np.sum(x_data, axis=0)
x_data1 = np.sum(x_data, axis=1)
x_data2 = np.sum(x_data, axis=2)

In [32]:
print(x_data0.shape)
print(x_data1.shape)
print(x_data2.shape)

(3, 4)
(2, 4)
(2, 3)


In [33]:
print(x_data0)
print(x_data1)
print(x_data2)

[[1000    4    6    8]
 [  10   12   14   16]
 [  18   20   22   24]]
[[1013   18   21   24]
 [  15   18   21   24]]
[[1008   26   42]
 [  10   26   42]]
